# Generated by Django 4.2.7 on 2024-06-04 12:41

from django.db import migrations, models
import django.db.models.deletion
import workersstat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine', models.CharField(blank=True, max_length=200, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('start_activity', models.DateTimeField(blank=True, null=True, verbose_name='start activity')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='last activity')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to=workersstat.models.get_upload_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='workersstat.user')),
            ],
        ),
    ]
