# Generated by Django 4.2.7 on 2024-06-04 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='screenshot',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='file',
            field=models.TextField(blank=True, db_column='data'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='workersstat.user'),
        ),
    ]
