# Generated by Django 4.2.7 on 2024-06-04 22:23

from django.db import migrations, models
import django.db.models.deletion
import workersstat.models


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0002_remove_screenshot_screenshot_screenshot_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='file',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='data',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=workersstat.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='workersstat.user'),
        ),
    ]
