# Generated by Django 4.2.7 on 2024-06-05 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0003_remove_screenshot_file_screenshot_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='data',
        ),
        migrations.AddField(
            model_name='screenshot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='last activity'),
        ),
    ]
