# Generated by Django 4.2.7 on 2024-06-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0004_remove_screenshot_data_screenshot_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenshot',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='created'),
        ),
    ]
