# Generated by Django 4.2.7 on 2024-06-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0006_user_get_screenshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='user',
            name='get_screenshots',
            field=models.BooleanField(default=False, verbose_name='Получать скриншоты рабочего стола (раз в 30 сек)'),
        ),
    ]
