# Generated by Django 4.2.7 on 2024-06-05 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0007_alter_user_options_alter_user_get_screenshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
