# Generated by Django 4.2.7 on 2024-06-05 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0008_alter_user_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='EmployerSession',
        ),
        migrations.AlterModelOptions(
            name='employersession',
            options={'verbose_name': 'Сессия/сотрудник', 'verbose_name_plural': 'Сессии сотрудников'},
        ),
        migrations.RenameField(
            model_name='screenshot',
            old_name='user',
            new_name='employee',
        ),
    ]
