# Generated by Django 4.2.7 on 2024-06-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0009_rename_user_employersession_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerSession',
            new_name='EmployeeSession',
        ),
    ]
