# Generated by Django 4.2.7 on 2024-06-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0011_rename_employeesession_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenshot',
            old_name='employee',
            new_name='session',
        ),
    ]
