# Generated by Django 4.2.7 on 2024-06-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0012_rename_employee_screenshot_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='domain',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
