# Generated by Django 4.2.7 on 2024-06-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersstat', '0013_session_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_activity',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='start activity'),
        ),
    ]
